import os
from dotenv import load_dotenv
load_dotenv()

# ENV
APP_ENV=os.getenv("APP_ENV")

# Main DB connection
DATABASE_NAME = os.getenv("DATABASE_NAME")
DATABASE_USER = os.getenv("DATABASE_USER")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
DATABASE_HOST = os.getenv("DATABASE_HOST")
DATABASE_PORT = os.getenv("DATABASE_PORT")

# RAILS DB connection

RAILS_DATABASE_NAME = os.getenv("RAILS_DATABASE_NAME")
RAILS_DATABASE_USER = os.getenv("RAILS_DATABASE_USER")
RAILS_DATABASE_PASSWORD = os.getenv("RAILS_DATABASE_PASSWORD")
RAILS_DATABASE_HOST = os.getenv("RAILS_DATABASE_HOST")
RAILS_DATABASE_PORT = os.getenv("RAILS_DATABASE_PORT")

# microservice
RUBY_ADDRESS_URL=os.getenv("RUBY_ADDRESS_URL") or "https://api.stage.cogoport.io"
RUBY_AUTHTOKEN = os.getenv('RUBY_AUTHTOKEN')
RUBY_AUTHSCOPE = os.getenv('RUBY_AUTHSCOPE')
RUBY_AUTHSCOPEID = os.getenv('RUBY_AUTHSCOPEID')
DEFAULT_USER_ID = "2dbe768e-929d-4e54-baf0-309ef68c978b"


COMMON_SERVICE_PORT=os.getenv("COMMON_SERVICE_PORT")
AUTH_SERVICE_PORT=os.getenv("AUTH_SERVICE_PORT")
COGOMAPS_SERVICE_PORT =os.getenv("COGOMAPS_SERVICE_PORT")
SPOT_SEARCH_PORT=os.getenv("SPOT_SEARCH_PORT")
CHECKOUT_PORT=os.getenv("CHECKOUT_PORT")
SHIPMENT_PORT=os.getenv("SHIPMENT_PORT")
INTERNAL_NLB=os.getenv("INTERNAL_NLB")

# Redis
REDIS_HOST=os.getenv("REDIS_HOST")
REDIS_PORT=os.getenv("REDIS_PORT")
REDIS_USERNAME=os.getenv("REDIS_USERNAME")
REDIS_PASSWORD=os.getenv("REDIS_PASSWORD")

# RAILS_REDIS_HOST=os.getenv("RAILS_REDIS_HOST")
# RAILS_REDIS_PORT=os.getenv("RAILS_REDIS_PORT")
# RAILS_REDIS_USERNAME=os.getenv("RAILS_REDIS_USERNAME")
# RAILS_REDIS_PASSWORD=os.getenv("RAILS_REDIS_PASSWORD")

CELERY_REDIS_URL = "rediss://{}:{}@{}:{}/0?ssl_cert_reqs=CERT_NONE".format(REDIS_USERNAME, REDIS_PASSWORD, REDIS_HOST, REDIS_PORT)
AWS_S3_BUCKET_NAME = os.getenv("AWS_S3_BUCKET_NAME")
AWS_S3_REGION_NAME = "ap-south-1"
SENTRY_DSN = os.getenv('SENTRY_DSN')